- ROADMAP.md
EngRes: please feel free to push edits directly to this branch; this is a collaboratively-edited document.
> docs: add Roadmap

- ROADMAP.md
- Make the milestones subbullets
- Add tracking issues
- Add two proposed milestones for 2023Q3
> docs: update Roadmap

- ROADMAP.md
Adds links to slides and video of talk.
Closes #7
> docs: add state of ipfs in js talk links to roadmap

- MANIFESTO.md
Some high-level thoughts behind the design rationale.
> docs: add manifesto

- packages/helia/package.json
- packages/helia/src/helia.ts
- packages/helia/src/index.ts
- packages/helia/src/storage.ts
- packages/helia/test/index.spec.ts
- packages/interface/src/index.ts
Default to using in-memory block/datastores if they aren't provided and a libp2p proxy that will throw if you invoke any of it's methods.
> fix: make all helia args optional

- packages/helia/package.json
- packages/helia/src/helia.ts
- packages/helia/test/gc.spec.ts
- packages/interface/src/index.ts
Pass an error event to the on progress handler if an error occurs during gc.
> fix: survive a cid causing an error during gc

- benchmarks/gc/package.json
- benchmarks/gc/src/README.md
- benchmarks/gc/tsconfig.json
https://github.com/tinylibs/tinybench/pull/33 has been merged so update the minimum used version
> chore: update benchmark

- packages/helia/src/storage.ts
- packages/helia/test/fixtures/create-block.ts
- packages/helia/test/fixtures/create-dag.ts
- packages/interface/src/blocks.ts
The blocks interface is `interface-blockstore` with extra progress events
> fix: update blocks interface to align with interface-blockstore

- benchmarks/gc/package.json
This was not done as part of the release because it's not in the workspaces list by default.
> chore: update helia and go-ipfs version in benchmark

- CODEOWNERS
Addresses: #35 
Adding @ipfs/helia-dev as CODEOWNERS.
> chore: Adds codeowners

- MANIFESTO.md
Refs #35
- Removes permissions section as it's not relevant to general usage
- Updates out of date sections and adds links to relevant modules
- Adds emojis
> docs: update manifesto

- ROADMAP.md
Added more adoption notes
Added js-ipfs deprecation tracking issue
Reframe → HTTP Routing v1
> docs: updated roadmap now that in 2023Q2

- packages/helia/package.json
- packages/helia/src/helia.ts
- packages/helia/src/index.ts
- packages/helia/src/utils/libp2p.browser.ts
- packages/helia/src/utils/libp2p.ts
- packages/helia/test/factory.spec.ts
- packages/helia/test/gc.spec.ts
- packages/helia/test/index.spec.ts
- packages/interface/package.json
- packages/interface/src/index.ts
- packages/interop/package.json
- packages/interop/test/blockstore.spec.ts
- packages/interop/test/fixtures/create-helia.browser.ts
- packages/interop/test/fixtures/create-helia.ts
- packages/interop/test/hashes.spec.ts
The original intention was to allow users to configure a libp2p node to their requirements but it's a non-trivial undertaking unless the user is deeply familiar with the libp2p stack.
Instead, let's provide node and browser libp2p instances with sensible defaults that give the user the best chance of success on first try.
Fixes #121
> feat: provide default libp2p instance

- packages/helia/package.json
- packages/helia/scripts/update-version.js
- packages/helia/src/index.ts
- packages/helia/src/version.ts
- packages/helia/test/factory.spec.ts
- packages/interface/package.json
- packages/interop/package.json
If the user has configured identify but not overridden the agent version, add helia and its version number to the string.
Fixes #122
> fix: add helia version to agent version

- packages/helia/src/utils/bootstrappers.ts
- packages/helia/src/utils/libp2p.browser.ts
- packages/helia/src/utils/libp2p.ts
List of bootstrap nodes is in one place now and links to the source.
Refs: https://github.com/ipfs/helia/pull/127#discussion_r1199152374
> fix: dedupe bootstrap list

- packages/helia/.aegir.js
- packages/helia/package.json
- packages/helia/src/helia.ts
- packages/helia/src/storage.ts
- packages/helia/src/utils/networked-storage.ts
- packages/helia/test/fixtures/create-helia.ts
- packages/helia/test/pins.spec.ts
- packages/helia/test/storage.spec.ts
- packages/helia/test/utils/networked-storage.spec.ts
- packages/interop/package.json
- packages/interop/test/pins.spec.ts
Creates a networked blockstore component that will pull missing blocks from the network when requested.
Passes this component to the pins component so when walking DAGs to pin blocks, and missing blocks will be fetched from peers.
Adds tests for the same.
> fix: ensure pinned blocks are present

- packages/helia/src/index.ts
- packages/helia/src/pins.ts
- packages/helia/test/pins.spec.ts
- packages/interface/src/pins.ts
To allow cancelling pin operations and getting progress events, pass the options to blockstore.get
> fix: pass options to blockstore.get during pin.add

- README.md
Adds a link in the docs to @helia/car - lets users import/export car files from Helia
> docs: add link to @helia/car

- README.md
The link was pointing to the @helia/dag-json instead of @helia/dag-cbor.
> docs: fix wrong link in README

- benchmarks/add-dir/README.md
Removes action item that was already addressed.
> docs: remove add-dir bench action item

- .github/workflows/main.yml
- .release-please-manifest.json
- .release-please.json
- package.json
- packages/helia/package.json
- packages/helia/typedoc.json
- packages/interface/package.json
- packages/interface/typedoc.json
- packages/interop/package.json
- typedoc.json
To enable releasing an RC with the new version of libp2p, switch to gated releases using release-please - config borrowed from libp2p.
> chore: use release-please for releases

- packages/helia/package.json
- packages/helia/src/pins.ts
- packages/helia/src/utils/dag-walkers.ts
- packages/helia/test/pins.spec.ts
Since the json codec is bundled with multiformats we should add a dag walker for it to allow pinning json blocks.
Fixes #246
> fix: add dag walker for json codec

- packages/helia/.aegir.js
- packages/helia/package.json
- packages/helia/test/pins.spec.ts
We previously had a circuit relay connection to the peer in the test, but circuit relay connections are transient (e.g. time/data limited) so we can't run bitswap over it.
Instead pull the block from the relay server as we can have a regular (non-transient) websocket connection to that peer.
> chore: pull block to pin from relay server instead of peer

- packages/helia/src/index.ts
- packages/helia/src/utils/libp2p-defaults.browser.ts
- packages/helia/src/utils/libp2p-defaults.ts
- packages/helia/src/utils/libp2p.ts
Updates return type of default libp2p service hash to include all configured services.
> fix: export libp2p service return type

- packages/helia/src/utils/libp2p-defaults.browser.ts
- packages/helia/src/utils/libp2p-defaults.ts
Make circuit relay the first transport to try so it will match addresses ahead of supporting transports.
E.g. where the address is `/<webtransport>/<circuit-relay>` get the circuit relay transport to dial first as it will strip off the relay part, hand control back to the transport manager and then run the circuit relay protocol over the newly created webtransport connection.
This is a tactical fix for a bug that needs to be addressed in libp2p.
> fix: try circuit relay transport first

- packages/helia/src/index.ts
- packages/helia/test/factory.spec.ts
The identify service does not pull the agent string from the peer store any more so attempt to update it on the service directly.
> fix: update attempt to add helia to identify agent version

- packages/helia/src/utils/libp2p-defaults.ts
Add libp2p config to listen on available IPv6 interfaces.
> fix: listen on ip6 addresses

- packages/helia/.aegir.js
- packages/helia/src/block-brokers/bitswap-block-broker.ts
- packages/helia/src/block-brokers/index.ts
- packages/helia/src/block-brokers/trustless-gateway-block-broker.ts
- packages/helia/src/index.ts
- packages/helia/src/utils/networked-storage.ts
- packages/helia/test/block-broker.spec.ts
- packages/helia/test/block-brokers/block-broker.spec.ts
- packages/helia/test/block-brokers/trustless-gateway-block-broker.spec.ts
- packages/interface/src/blocks.ts
- feat: blockBrokers can control block validation
Built on top of https://github.com/ipfs/helia/pull/281 & https://github.com/ipfs/helia/pull/284
This PR adds the `validateFn` option to `BlockRetriever.retrieve` options and slightly modifies
how `raceBlockRetrievers` inside of `NetworkedStorage` is handled. Some callouts:
* BlockBroker's are given a TRUSTED `validateFn` to call when they retrieve blocks, and MAY call this method prior to returning the block
* If they call `validateFn`, when
* it doesn't throw, we consider the blocks to have been verified (since we own the inner `validateFn` and given MultihashHashers)
* it throws, they can handle recourse within their `retrieve` method (e.g. try other gateways, other peers/transports/etc, whatever they want)
* If they do not, we consider …
> feat: blockBrokers can control block validation

- packages/helia/.aegir.js
- packages/helia/src/block-brokers/bitswap-block-broker.ts
- packages/helia/src/block-brokers/index.ts
- packages/helia/src/block-brokers/trustless-gateway-block-broker.ts
- packages/helia/src/helia.ts
- packages/helia/src/index.ts
- packages/helia/src/utils/networked-storage.ts
- packages/helia/test/block-brokers/block-broker.spec.ts
- packages/helia/test/block-brokers/trustless-gateway-block-broker.spec.ts
- packages/helia/test/fixtures/create-helia.ts
- packages/helia/test/pins.depth-limited.spec.ts
- packages/helia/test/pins.recursive.spec.ts
- packages/helia/test/utils/networked-storage.spec.ts
- packages/interface/src/blocks.ts
- packages/interface/src/index.ts
- packages/interop/test/fixtures/create-helia.browser.ts
- packages/interop/test/fixtures/create-helia.ts
Adds on to changes from https://github.com/ipfs/helia/pull/280 and https://github.com/ipfs/helia/pull/281
This makes it much easier to support constructing helia with custom blockBrokers while still allowing consumers easy access to the default BitswapBlockBroker. One particular use-case where this comes in handy: our tests.
Take the code in `packages/helia/test/fixtures/create-helia.ts` for example. Without these changes, you have to do something like:
```typescript
import { webSockets } from '@libp2p/websockets'
import * as Filters from '@libp2p/websockets/filters'
import { MemoryBlockstore } from 'blockstore-core' // new import
import { MemoryDatastore } from 'datastore-core' // new import
import { circuitRelayTransport } from 'libp2p/circuit-relay'
import { identifyService } from …
```
> feat: BlockBroker factory support

- packages/helia/.aegir.js
- packages/helia/src/block-brokers/bitswap.ts
- packages/helia/src/block-brokers/index.ts
- packages/helia/src/block-brokers/trustless-gateway/broker.ts
- packages/helia/src/block-brokers/trustless-gateway/index.ts
- packages/helia/src/block-brokers/trustless-gateway/trustless-gateway.ts
- packages/helia/src/helia.ts
- packages/helia/src/index.ts
- packages/helia/test/block-brokers/block-broker.spec.ts
- packages/helia/test/block-brokers/trustless-gateway.spec.ts
- packages/helia/test/fixtures/create-helia.ts
- packages/helia/test/utils/networked-storage.spec.ts
- packages/interface/src/index.ts
- packages/interop/test/fixtures/create-helia.browser.ts
- packages/interop/test/fixtures/create-helia.ts
This approach is consistent with libp2p components, unixfs, ipns, etc.
Since #281 and #284 were merged without review, this PR implements suggestions that would have been in the review of those PRs.
1. Creation of block brokers is done by exported function. If your broker takes arguments, pass them to the factory function.  The factory then returns a function that accepts helia components and returns the broker.
2. Removes BitswapBlockBrokerFactory variable in favour of `bitswap` function
3. Removes BlockBrokerFactoryComponents interface in favour of brokers declaring their own component requirements
4. Define DEFAULT_TRUSTLESS_GATEWAYS in trustless gateway code
5. Use `await expect(promise).to.eventually.be.rejected` in tests instead of `try/catch` blocks
6. Remove use of console
The …
> refactor: use functions for block broker creation

- .github/workflows/main.yml
- .github/workflows/semantic-pull-request.yml
- README.md
- package.json
- packages/helia/README.md
- packages/helia/src/index.ts
- packages/helia/typedoc.json
- packages/interface/README.md
- packages/interface/src/index.ts
- packages/interface/typedoc.json
- packages/interop/README.md
- typedoc.json
Updates to latest aegir version with simplified readmes, auto-copying @packageDocumentation to "About" section and includes version numbers in the module versions.
> docs: update generated docs to include version in module names

- packages/helia/src/block-brokers/trustless-gateway/index.ts
tested at https://codepen.io/SgtPooki/pen/JjxYpZX successfully.
> feat: use trustless-gateway.link by default

- packages/helia/src/block-brokers/trustless-gateway/index.ts
Removes `trustless-gateway.link`. We can reinstate once it's been removed from the bad list.
> fix: remove trustless-gateway.link

- packages/block-brokers/src/trustless-gateway/index.ts
Note that w3s will only serve blocks that are uploaded to it.
For those that do use w3s for uploading files, they just need to pass the defaults + the gateways they want
```
// heliaInit config:
blockBrokers: [ 
trustlessGateways({ 
gateways: [
...DEFAULT_TRUSTLESS_GATEWAYS, 
'https://w3s.link'
]
})
]
```
> fix: remove w3s.link default block-broker

- packages/helia/src/index.ts
- packages/helia/test/libp2p.spec.ts
Omits the `start` key from the accepted libp2p init params, instead use only the `start` key in the main Helia init object.
Fixes #344
> fix: ignore libp2p start param in helia factory

- packages/helia/package.json
- packages/helia/src/utils/libp2p-defaults.browser.ts
- packages/helia/src/utils/libp2p-defaults.ts
- packages/interop/package.json
- packages/interop/src/fixtures/connect.ts
- packages/interop/src/fixtures/create-helia.browser.ts
- packages/interop/src/fixtures/create-helia.ts
- packages/interop/src/ipns-pubsub.spec.ts
- packages/ipns/README.md
- packages/ipns/src/index.ts
It's not required to IPFS things, it's a large chunk of code and it's quite CPU intensive so do not bundle it by default.
People can still configure themselves if they need it.
> fix!: remove gossipsub from default libp2p services

- packages/interop/src/ipns-http.spec.ts
- packages/interop/src/ipns-pubsub.spec.ts
- packages/interop/src/ipns.spec.ts
- packages/ipns/README.md
- packages/ipns/src/index.ts
- packages/ipns/test/publish.spec.ts
- packages/ipns/test/resolve-dns.spec.ts
- packages/ipns/test/resolve.spec.ts
- fix: @helia/ipns doesn't enforce no-path
- feat!: ipns resolve supports paths (#402)
fixes https://github.com/ipfs/helia/issues/402
We will likely want to add support for publishing with paths as well, https://github.com/ipfs/helia/blob/e5544935a4c4444bdfd77a85fa247503614a5a9d/packages/ipns/src/index.ts#L316 but I may need to understand nuance to implement that
BREAKING CHANGE: `@helia/ipns` resolve now supports paths, so the return type is now `{ path: string, cid: CID }` instead of just `CID`
**Before**
```typescript
const cidFromPeerId = await ipns.resolve(peerId)
const cidFromDnsLink = await ipns.resolve(domainName)
```
**After**
```typescript
const { cid, path } = await ipns.resolve(peerId)
const { cid, path } = await ipns.resolve(domainName)
```
> feat!: support paths in @helia/ipns

- packages/verified-fetch/src/index.ts
- packages/verified-fetch/test/index.spec.ts
To allow no-option, all-defaults construction of verified fetch
```TypeScript
import { createVerifiedFetch } from '@helia/verified-fetch'
const fetch = await createVerifiedFetch()
const resp = await fetch('ipfs://bafy...')
// ...
```
> fix: @helia/verified-fetch init args are optional

- packages/verified-fetch/package.json
- packages/verified-fetch/test/verified-fetch.spec.ts
The stub should be for the `Blocks` interface.
> chore: stub blocks interface in tests

- packages/verified-fetch/README.md
- packages/verified-fetch/src/index.ts
- packages/verified-fetch/src/singleton.ts
- packages/verified-fetch/test/index.spec.ts
This might make things even easier to get started?  It exports a singleton version of verified fetch that creates the backing Helia node on the first fetch access, transparent to the user.
```TypeScript
import { verifiedFetch } from '@helia/verified-fetch'
const response = await verifiedFetch('ipfs://Qmfoo')
console.info(await response.json())
```
It's not in this PR but maybe we'd want to allow some config:
```TypeScript
import { verifiedFetch } from '@helia/verified-fetch'
const response = await verifiedFetch('ipfs://Qmfoo', {
gateways: ['https://...']
})
console.info(await response.json())
```
Calling this twice with different gateways might result in an error.
```TypeScript
import { verifiedFetch } from '@helia/verified-fetch'
const response1 = await verifiedFetch('ipfs://Qmfoo', { …
```
> feat: allow use as a singleton

- packages/ipns/package.json
- packages/ipns/src/utils/dns.ts
We only use `is-ipfs` to detect if a string contains a `CID`, just try to parse it instead to save a large depdendency.
> fix: remove is-ipfs from @helia/ipns dependencies

- packages/interop/src/verified-fetch-json.spec.ts
- packages/interop/src/verified-fetch-unixfs-dir.spec.ts
- packages/interop/src/verified-fetch-websites.spec.ts
- packages/verified-fetch/src/index.ts
fixes an issue where createVerifiedFetch would not allow both:
- a custom Helia instance
- a custom contentTypeParser
> fix: allow contentTypeParser with Helia instance

- packages/car/package.json
- packages/dag-cbor/package.json
- packages/dag-json/package.json
- packages/helia/package.json
- packages/http/package.json
- packages/json/package.json
- packages/mfs/package.json
- packages/strings/package.json
- packages/unixfs/package.json
- packages/utils/package.json
- packages/utils/src/utils/networked-storage.ts
- packages/utils/test/utils/networked-storage.spec.ts
Use a tiered blockstore that combines an identity blockstore with the configured blockstore to support reading identity CIDs.
> fix: support reading identity cids

- packages/verified-fetch/src/index.ts
- packages/verified-fetch/src/verified-fetch.ts
- packages/verified-fetch/test/verified-fetch.spec.ts
Do not stringify CIDs before using them as events.
The user can do this if they want, parsing them back to objects is not free.
I'm not sure why these were strings in the first place.
> fix: use CID object for verified-fetch progress events

- packages/verified-fetch/package.json
- packages/verified-fetch/src/verified-fetch.ts
- packages/verified-fetch/test/fixtures/create-offline-helia.ts
- packages/verified-fetch/test/verified-fetch.spec.ts
The extensive stubbing in the `@helia/verified-fetch` tests have some baked-in assumptions about how the codecs work which are not easy to unpick.
It's quick to test using the actual codecs if the block data is already present so remove the stubs and use a network-less Helia node to make the tests more reliable.
> fix: remove stubs from verified-fetch tests

- packages/verified-fetch/src/index.ts
Refine the verified-fetch README
> docs: refine verified fetch docs

- packages/car/package.json
- packages/car/src/index.ts
- packages/car/test/fixtures/dag-walkers.ts
- packages/car/test/index.spec.ts
- packages/car/test/stream.spec.ts
To better support streaming CAR files with a less confusing API, add a method to `@helia/car` that takes root CIDs and returns an AsyncGenerator that yields CAR file bytes.
> feat: stream car file bytes from @helia/car

- packages/car/test/index.spec.ts
The test introduces an artificially small block size to ensure we have a CAR file with lots of blocks but it's quite slow and often causes CI failures.
The large file being added to the CAR file is already big enough to be formed of multiple blocks so splitting it into many smaller blocks doesn't give us much.
> chore: fix multiblock car file test

- packages/ipns/src/dnslink.ts
- packages/ipns/src/index.ts
- packages/ipns/test/resolve-dnslink.spec.ts
Hitting external services can be flaky as we see periodic failures in CI for `ipfs.io` and friends so add a retry.
> fix: add retries for dnslink

- packages/ipns/src/dnslink.ts
- packages/ipns/src/index.ts
- packages/ipns/test/resolve-dnslink.spec.ts
- packages/ipns/test/resolve.spec.ts
Adds fields to IPNS results:
`record`: present in the return from `ipns.resolve` - contains the resolved IPNS record.
`answer`: present in the return from `ipns.resolveDNSLink` - contains the resolved DNS Answer.
> feat: add `record`/`answer` fields to IPNS results

- packages/interop/src/ipns.spec.ts
As per discussion in https://github.com/ipfs/helia-verified-fetch/pull/34#discussion_r1541129095 this adds a check to ensure correct TTL interop for IPNS records between @helia/ipns and Kubo.
> test: test ipns ttl interop

- packages/unixfs/src/utils/glob-source.ts
fix: Add GlobSourceResult to globSource return type.
This is a small PR that modifies the return type on the `globSource` utility in `@helia/unixfs` to return the `GlobSourceResult` in addition to the `ImportCandidate` type. This means that the `path` property will be a `string` instead of `string | undefined`.
This PR makes it a bit easier to use `globSource` since it is a bit annoying to have to check if `path` is defined when it always is.
Is there any reason why we had the `GlobSourceResult` type but `globSource` does not return it?
> fix: Add GlobSourceResult to globSource return type in unixfs.

- packages/ipns/package.json
- packages/ipns/src/index.ts
- packages/ipns/src/routing/local-store.ts
- packages/ipns/src/routing/pubsub.ts
- packages/ipns/test/publish.spec.ts
- packages/ipns/test/resolve.spec.ts
Uses the `@libp2p/record` `timeReceived` property and the `.ttl` field of the IPNS Record to calcuate the TTL of the record separately from the record EOL.
This was going to be a push to #473 but it was merged prematurely.
Fixes #479
> fix: respect the IPNS TTL field

- packages/bitswap/src/bitswap.ts
- packages/utils/src/utils/networked-storage.ts
To prevent spurious warnings appearing in the console, increase the number of listeners on created abort signals.
> fix: increase default listers on abort signals

- packages/utils/src/utils/networked-storage.ts
- packages/utils/test/utils/networked-storage.spec.ts
If multiple brokers are configured, when one resolves a block request,
cancel the outstanding requests to free up resources.
> fix: cancel in-flight block requests when racing brokers

- packages/bitswap/src/bitswap.ts
- packages/bitswap/src/network.ts
- packages/bitswap/src/peer-want-lists/index.ts
- packages/bitswap/src/session.ts
- packages/bitswap/src/stats.ts
- packages/bitswap/src/want-list.ts
- packages/bitswap/test/bitswap.spec.ts
- packages/bitswap/test/network.spec.ts
- packages/bitswap/test/peer-want-list.spec.ts
- packages/bitswap/test/stats.spec.ts
- packages/bitswap/test/want-list.spec.ts
Fixes a bug where sometimes a wanted CID was not removed from the wantlist when it was retrieved by an alternative block retriever.
Also switches to using events for block/presence arrival to remove shared promises.
> fix: remove wants from wantlist when multiple block retrievers are used

- packages/utils/src/storage.ts
- packages/utils/test/storage.spec.ts
If an aborted `AbortSignal` is passed to blockstore operations, the operation should throw an `AbortError`.
> fix: blockstore operations should throw when passed an aborted signal

- packages/block-brokers/.aegir.js
- packages/block-brokers/package.json
- packages/block-brokers/src/trustless-gateway/trustless-gateway.ts
- packages/block-brokers/test/trustless-gateway.spec.ts
- chore: add @types/polka
- feat: getStats() returns trustless gateway stats
fix: prevent duplicate trustless-gateway reqs
Fixes https://github.com/ipfs-shipyard/service-worker-gateway/issues/104
This PR fixes issues brought up in service-worker-gateway where sub-resources end up causing multiple requests to a trustless gateway for the root CID.
I feel like the blockstore should handle this and ensure requests that depend on a root CID are deduped, but since trustless-gateways may be used outside of the context of blockstores, I believe we still need this improvement.
> fix: prevent duplicate trustless-gateway reqs

- packages/unixfs/src/commands/add.ts
- packages/unixfs/src/commands/cat.ts
- packages/unixfs/src/commands/chmod.ts
- packages/unixfs/src/commands/cp.ts
- packages/unixfs/src/commands/ls.ts
- packages/unixfs/src/commands/mkdir.ts
- packages/unixfs/src/commands/rm.ts
- packages/unixfs/src/commands/stat.ts
- packages/unixfs/src/commands/touch.ts
- packages/unixfs/src/commands/utils/add-link.ts
- packages/unixfs/src/commands/utils/cid-to-directory.ts
- packages/unixfs/src/commands/utils/cid-to-pblink.ts
- packages/unixfs/src/commands/utils/dir-sharded.ts
- packages/unixfs/src/commands/utils/hamt-utils.ts
- packages/unixfs/src/commands/utils/is-over-shard-threshold.ts
- packages/unixfs/src/commands/utils/persist.ts
- packages/unixfs/src/commands/utils/remove-link.ts
- packages/unixfs/src/commands/utils/resolve.ts
- packages/unixfs/src/index.ts
- packages/unixfs/src/unixfs.ts
We only use the get/put/has methods from the blockstore interface so pick those methods to allow easy use from other codebases.
> fix: relax unixfs blockstore input type

- packages/block-brokers/src/trustless-gateway/trustless-gateway.ts
Node's `undici` module appears to be adding listeners for the `"abort"` event on any passed AbortSignal but then not cleaning them up.
This casues many `MaxListenersExceededWarning`s to appear in the console and likely causes a memory leak.
To work around this, use a short-lived `AbortSignal` for each request that can be garbage collected along with the request itself and trigger `"abort"` on it if the long-lived signal aborts, taking care to remove any added listeners once we are done with the request.
See https://github.com/nodejs/node/issues/52635 for more information.
> fix: use a short-lived AbortSignal for fetch operations

- packages/bitswap/src/network.ts
- packages/bitswap/src/peer-want-lists/index.ts
- packages/bitswap/src/stats.ts
- packages/bitswap/src/want-list.ts
- packages/bitswap/test/stats.spec.ts
- packages/helia/src/index.ts
- packages/interface/src/index.ts
- packages/utils/src/index.ts
- packages/utils/test/index.spec.ts
To allow collecting metrics about arbitrary parts of the Helia stack, add an optional `.metrics` property for stat collection.
This can be used with implementations such as `@libp2p/prometheus-metrics` and/or others.
> feat: add metrics property to helia interface

- packages/utils/src/routing.ts
When a routing returns a set of multiaddrs, honour them as returned instead of appending the peer id to them.
> fix: do not append peer ids to provider multiaddrs

- packages/routers/package.json
- packages/routers/src/http-gateway-routing.ts
- packages/routers/src/index.ts
- packages/routers/test/http-gateway-routing.spec.ts
Adds a routing implementation that returns a static list of gateways as providers for CIDs.
It's expected that these gateways are able to fetch content on our behalf.
Depends on:
> feat: add static http gateway routing

- packages/unixfs/package.json
- packages/unixfs/src/utils/glob-source.browser.ts
- packages/unixfs/src/utils/glob-source.ts
Updates it-glob to use fast-glob for a speedup vs minimatch.
> deps: update it-glob

- packages/helia/src/utils/bootstrappers.ts
It's unmaintained, unsupported and errors all the time.
> fix: remove rust bootstrapper

- packages/ipns/test/resolve.spec.ts
Slow CI is slow so I think the TTL is expiring during the test leading to flaky CI.
> chore: increase record ttl in ipns test

- packages/block-brokers/.aegir.js
The trustless gateway block broker should be used with a http gateway router which will supply a default set of gateways in a way usable by other consumers of the Helia routing.
This was mistakenly released in `@helia/block-brokers@2.1.2` which has been reverted, this PR will cause `@helia/block-brokers@3.0.0` to be released.
Before:
```js
import { createHelia } from 'helia'
import { trustlessGateway } from '@helia/block-brokers'
import { delegatedHTTPRouting } from '@helia/routers'
await createHelia({
blockBrokers: [
trustlessGateway({
gateways: [
'http://example.com'
]
})
],
routers: [
delegatedHTTPRouting('https://delegated-ipfs.dev')
],
//... other settings
})
```
After:
```js
import { createHelia } from 'helia'
import { trustlessGateway } from '@helia/block-brokers'
import { …
```
> fix!: trustless gateway brokers no longer take a gateways arg

- packages/utils/src/abstract-session.ts
Fixes an issue on queue generic: `Type '{ provider: Provider; priority?: number | undefined; }' has no properties in common with type 'AbortOptions'.ts(2559)`
> fix: type error

- packages/interop/src/ipns-dnslink.spec.ts
Dependency on third-party domains means  that over time CI will break, like it did in
https://github.com/ipfs/kubo/actions/runs/9214249430/job/25364989609?pr=10429#step:9:63
```
Error: queryCname ENODATA singularity.storage
```
The three domains I left are stable and under IPFS Foundation / Shipyard control.
Ideally, CI would not depend on internet DNS, and have static fixtures and custom localhost DNS server, but this PR should be good enough to stop breaking CI on other project's PRs like https://github.com/ipfs/kubo/pull/10429
> fix: do not depend on external domains in dnslink tests

- packages/helia/src/utils/libp2p-defaults.ts
Circuit relay servers no longer advertise themselves.
> fix: update circuit relay server args

- packages/helia/src/index.ts
- packages/helia/src/utils/libp2p-defaults.browser.ts
- packages/helia/src/utils/libp2p-defaults.ts
- packages/helia/test/libp2p.spec.ts
- packages/interop/src/fixtures/create-helia.browser.ts
- packages/interop/src/fixtures/create-helia.ts
After the last js-libp2p release, tsc now decides that the service factory map has a type and libp2p itself is better at detecting invalid configurations so we need to be stricter about how we create libp2p options.
> fix: update js-libp2p types

- packages/bitswap/README.md
- packages/block-brokers/README.md
- packages/car/README.md
- packages/dag-cbor/README.md
- packages/dag-json/README.md
- packages/helia/README.md
- packages/http/README.md
- packages/interface/src/blocks.ts
- packages/interop/README.md
- packages/ipns/README.md
- packages/json/README.md
- packages/mfs/README.md
- packages/routers/README.md
- packages/strings/README.md
- packages/unixfs/README.md
- packages/utils/README.md
Fix grammar: it's -> its
A few places use "it's" (= it is), when they should use the possessive "its" (the dog and its ball).
> docs: fix grammar - it's -> its

- benchmarks/add-dir/package.json
- benchmarks/gc/package.json
- benchmarks/transfer/package.json
- benchmarks/transports/package.json
- packages/bitswap/src/network.ts
- packages/utils/src/index.ts
TSC picks up a couple of new type errors when all deps are updated to their latest versions.
> fix: update deps and fix types

- packages/block-brokers/src/trustless-gateway/utils.ts
- packages/block-brokers/test/trustless-gateway-utils.spec.ts
fix: Update filtering logic to respect secure contexts and enhance related tests
This PR addresses issue #564 by modifying the multiaddr filtering logic in the trustless-gateway module to ensure that allowInsecure: false respects Secure Contexts.
IP Address Filtering:
Modified the filter to ensure that when allowInsecure is false, a multiaddr with "127.0.0.1" as the IP address will still be considered valid. This addresses the need to handle secure contexts properly even when allowInsecure is disabled.
Domain Filtering:
Adjusted the filter to ensure that when allowInsecure is false, a multiaddr with "localhost" as the domain will be treated as valid.
Updated the filter to handle domains with a parent domain of "localhost", such as example.localhost, foobar.localhost, and *.localhost. …
> fix: Adjust filtering logic for secure contexts; improve tests

- packages/interop/src/ipns-pubsub.spec.ts
IPNS interop tests for helia→pubsub→kubo did not execute the same tests as kubo→pubsub→helia.
Namely, publishing to IPNS was executed with assumption it will fail, as a convoluted way of confirming the kubo is not subscribed to the topic, and also kubo connectivity state is somehow taken on belief, rather than being programmatically verified:
```js
// first publish should fail because kubo isn't subscribed to key update channel
await expect(name.publish(peerId, cid)).to.eventually.be.rejected()
.with.property('message', 'PublishError.NoPeersSubscribedToTopic')
// should fail to resolve the first time as kubo was not subscribed to the pubsub channel
await expect(last(kubo.api.name.resolve(peerId, {
timeout: 100
}))).to.eventually.be.undefined()
```
Good news is that there are native APIs …
> fix: test for subscribers to ipns pubsub topic

- packages/interop/package.json
- packages/interop/src/ipns-pubsub.spec.ts
- packages/utils/src/index.ts
No need to duplicate the function now.
> fix: use hasCode from multiformats

- packages/interface/src/pins.ts
The record values are added as `string | number | boolean` so reflect that in the listed type.
BREAKING CHANGE: the metadata record value field has changed from `any` to `string | number | boolean`
> fix!: define string metadata type

- README.md
docs: add custom hasher example to readme
Adds an example to the readme of how to use a custom hasher with the helia data importing utils.
Closes: #640
Would love feedback on wording etc. @2color
> docs: add custom hasher example to readme

- packages/helia/package.json
- packages/interop/package.json
- packages/interop/src/fixtures/create-helia.ts
- packages/ipns/package.json
Updates dep to pull in performance improvements.
> deps: update kad-dht to 14.0.0

- packages/helia/src/index.ts
- take the passed routers config in createHelia into acount
This PR allows overriding the routers configuration when customising Helia. Useful when you want to exclusively fetch directly from peers without relying on recursive gateways.
In `@helia/http` we already do this:
https://github.com/ipfs/helia/blob/332580c4dd1646381bfeedd7741e52bc3a364301/packages/http/src/index.ts#L79-L82
> fix: respect routers config in helia factory

- packages/helia/package.json
- packages/helia/src/utils/libp2p-defaults.browser.ts
- packages/helia/src/utils/libp2p-defaults.ts
- **deps: upgrade delegated routing client**
- **feat: leverage filtering for delegated routing in libp2p constructor**
> feat: enable filtering in delegated routing client

- .aegir.js
- README.md
- This PR removes the config which sets the custom domain used for GitHub pages. Historically, the docs were deployed to the helia.io domain, however, since we introduced a website for the docs, we no longer want this. 
- When a custom domain is configured, Github will redirect from the github.io domain to the custom domain
- fixes https://github.com/ipfs/helia/issues/655 
I have also manually removed the custom domain from the site config to ensure this works.
> fix: remove helia.io cname 

- packages/helia/src/utils/libp2p-defaults.browser.ts
- packages/helia/src/utils/libp2p-defaults.ts
- packages/routers/src/index.ts
- packages/routers/src/utils/delegated-http-routing-defaults.browser.ts
- packages/routers/src/utils/delegated-http-routing-defaults.ts
- **fix: add tls to all default filters**
- **chore: avoid duplication of filters**
Should we just move these defaults to the [Delegated Routing client](https://github.com/ipfs/helia-delegated-routing-v1-http-api/blob/main/packages/client/src/client.ts#L26)?
> fix: add tls to default delegated routing filters

- packages/interface/src/routing.ts
- packages/routers/src/delegated-http-routing.ts
- packages/routers/src/libp2p-routing.ts
- packages/routers/test/libp2p-routing.spec.ts
- packages/utils/src/routing.ts
Exposes the cancel reprovide functionality of the libp2p routers.
> feat: add cancelReprovide function to routing

- FUNDING.json
Add FUNDING.json indicating that this repo is owned/maintained by Shipyard.
> chore: create FUNDING.json

- packages/ipns/src/dnslink.ts
- packages/ipns/test/resolve-dnslink.spec.ts
fixes https://github.com/ipfs/helia/issues/721
> fix: handle dnslink pointing to  CID with peer id (ipns name)

- packages/helia/package.json
- packages/helia/src/utils/libp2p-defaults.ts
Replaces the WebRTC listener with a WebRTC-Direct one under Node.js so the Helia instance can accept incoming dials without also needing a relay reservation.
> feat: add WebRTC-Direct listener

- packages/ipns/src/index.ts
- packages/ipns/test/publish.spec.ts
chore(ipns): align implicit default ttl with specs
- lowering TTL to 5m due to https://github.com/ipfs/specs/pull/492 
- raised lifetime  to 48h to match [recommendation from specs](https://specs.ipfs.tech/ipns/ipns-record/#validity-bytes) (48h, to at least match Amino DHT expiration window)
> fix: align implicit default ttl with specs

- packages/interop/src/car.spec.ts
- packages/interop/src/unixfs-bitswap.spec.ts
- packages/interop/src/unixfs-files.spec.ts
- packages/mfs/src/index.ts
Switch away from `addFile` as it will require paths after #754
These changes are backwards compatible, unlike #754
> fix: use bytestream methods to add byte streams

- packages/ipns/package.json
- packages/ipns/src/index.ts
Small refactor to use `peerIdFromString` in `@libp2p/peer-id` which now accepts CID encoded PeerIDs.
> chore: use peer id parsing function from libp2p

- packages/ipns/src/index.ts
- packages/ipns/src/utils.ts
- packages/ipns/test/republish.spec.ts
Fixes https://github.com/ipfs/helia/pull/745#discussion_r1992956518
> fix: handle /ipns/ prefixed keys in republishRecord

- packages/car/src/index.ts
docs: update @helia/car export method example
Fixes an issue with the example with invalid code.
* removed `await` from `c.export` because that results in an error in node.js v22.9.0:
```
Warning: Detected unsettled top-level await at file:///Users/sgtpooki/code/work/protocol.ai/ipfs/helia/packages/car/test.js:29
await c.export(cid, writer)
^
```
* removed pEvent listening on wrong (`end`) event, which doesn't exist in LTS: https://nodejs.org/docs/latest-v22.x/api/stream.html
Tested with code locally:
```js
import fs from 'node:fs'
import path from 'node:path'
import { cwd } from 'node:process'
import { Readable } from 'stream'
import { car } from '@helia/car'
import { createHeliaHTTP } from '@helia/http'
import { createVerifiedFetch } from '@helia/verified-fetch'
import { CarWriter } …
```
> docs: update @helia/car export method example

- packages/routers/src/http-gateway-routing.ts
- packages/routers/test/http-gateway-routing.spec.ts
See #771 for motivation.
For use cases where gateway lookup order is important, this PR allows passing a new config param to `HTTPGatewayRouter` which opts out of the shuffling which happens on each call to `findProviders`.
- The new param is optional
- Default value preserves the original behavior
I.e., the feature is backward-compatible.
> feat: add provider shuffle option to HTTPGatewayRouter

- packages/block-brokers/.aegir.js
- packages/block-brokers/test/trustless-gateway-sessions.spec.ts
- packages/utils/src/abstract-session.ts
- packages/utils/test/abstract-session.spec.ts
We originally did not abort when the session was idle because a block may have been found.
This PR changes that so that we have a race condition on signal.abort and foundBlock, but I believe this small window is a better situation than having the session never end (as in #775)
> fix: trustless-gateway sessions handle aborts properly 

- packages/helia/src/index.ts
- packages/helia/src/utils/helia-defaults.ts
- packages/helia/src/utils/libp2p.ts
- packages/http/src/index.ts
To make it easier to customise the default Helia settings, export a `heliaDefaults` function similar to the existing `libp2pDefaults` function.
> feat: export default helia config

- packages/block-brokers/README.md
- packages/dag-cbor/README.md
- packages/dag-json/README.md
- packages/unixfs/README.md
Fixes any `API Docs` links for packages that look like `@scope/name-name2` because they were incorrectly linking to `_scope_name_name2` instead of `_scope_name-name2`. 
I thought it could be an error in `aegir` but it seems like `npm run docs` doesn't reset the `API Docs` section entry at all.
> docs: fix API docs link

- packages/car/src/index.ts
- packages/dag-cbor/src/index.ts
- packages/dag-json/src/index.ts
- packages/interop/package.json
- packages/interop/src/providers.spec.ts
- packages/strings/src/index.ts
- packages/unixfs/src/index.ts
Allows pre-seeding transfer sessions with known providers if they are available.
> feat: expose providers option
