.github/dependabot.yml, .github/workflows/automerge.yml, .github/workflows/main.yml, .gitignore, .npmrc, LICENSE, LICENSE-APACHE, LICENSE-MIT, lerna.json, package.json
Adds github files for CI releases and dep/config updates.
=> chore: add ci files

ROADMAP.md
Added more specifics around driving adoption.
=> docs: updated roadmap

benchmarks/gc/package.json, packages/helia/package.json, packages/interop/package.json
=> fix: use release version of libp2p

.github/workflows/main.yml, .release-please-manifest.json, .release-please.json
release-please really doesn't like non-default branch names. Or something else, either way it keeps flailing around until it hits api limits so let's just do regular releases here.
=> chore: switch to non-gated releases

README.md
=> docs: added link to helia demos

README.md
Doing some items I saw while looking fresh at https://github.com/ipfs/helia/issues/35
This includes:
1. Moving contribution section up higher since this is important.
2. Updating the status section.
3. Combining about "code structure" both internally and as it relates to other projects.
4. Added a "notable users" section as a call that we'd like to hear from users and fill this in.
5. (bonus - feel free to reject) added some emojis for more color on the page.
=> docs: readme tidyup (status, organization, etc.)

README.md
=> docs: add system diagram

README.md
fix code on readme `dagCbor` code example
=> fix: use `dagCbor`

packages/helia/package.json, packages/helia/src/utils/libp2p-defaults.browser.ts, packages/helia/src/utils/libp2p-defaults.ts, packages/interop/package.json
This should have been in the previous release.
=> fix: enable dcutr by default

README.md
Refs: https://github.com/ipfs/helia-mfs/issues/3
=> docs: add link to @helia/mfs to root readme

README.md
This PR improves the way Helia is introduced both in this repo and to visitors of the helia.io website
=> docs: Improve introduction in monorepo README.md

.github/workflows/main.yml
Tell codecov where the coverage files are written to.
=> chore: specify code coverage locations

README.md
fixes https://github.com/ipfs/helia/issues/272
Adds blockBrokers to system diagram. 
[Check out live](https://mermaid.live/edit#pako:eNqFk91u4jAQhV8l8jWFkLCJSaXVCqEuSBWqGnrTphcmGYpFElv-WUoR716bhELkVpsb29-cGY-P4wPKWQEoQVn9JgjfeMvpbVZ75nuSIF4yZAePCY9wXtKcKMrqDL3e3PyePyxSE_-zgZKSAeW1NPwq10ieavp-dyXSZr12Zfd0xQPeZVOiiFRMQBdPSpZvO_y0xXcR2983haReNQc9teS9zOzw2sQ870t9Bpey5z0mgm1ByNuOooVWQ5XcEf5TeCm0VCVI-Zco2JH9pU7jgu14tnThg16leuVyc8q5Sx9hLUh1PjLURTNxD5OaBXkDc0V3tARP7qWCajCfTgZpOACVX-7qy5nW00vmPfyD0uptWien9cJkLEDtmNi23DHBKNrp8P-Sxbmj2dKp3NjkYOuSA1uTrjjqoQpERWhhHsTBqjKkNlBBhhIzLWBNdKky81aORkq0Yum-zlGihIYe0rwwDU4pMf9XhZI1KaWhnNQoOaB3lAzHft8PQx8HOPBH2B9HPbRHSRz3gxD_iqM4jKIAR-NjD30wZir4fTwahnEQ-eNhiEcY41O551PQ7nn8BGa3Lfk)
=> docs(diagram): add blockBrokers to system diagram

packages/interop/package.json, packages/interop/src/bin.ts
Otherwise it can't find the tests.
=> fix: include aegir config in interop and run from install dir

packages/ipns/src/index.ts
export IPNSRoutingEvents type for onProgress events
fixes https://github.com/ipfs/helia/issues/406
=> fix: export IPNSRoutingEvents

packages/interop/src/ipns-dnslink.spec.ts
These tests are flaky in CI so add a retry
=> chore: retry dnslink tests

packages/ipns/CHANGELOG.md
Fixes the order of the generated changelog.
Not sure why it wasn't in the right order 🤷‍♂️
=> chore: correct order in ipns changelog

packages/car/package.json, packages/dag-cbor/package.json, packages/dag-json/package.json, packages/helia/package.json, packages/http/package.json, packages/interface/package.json, packages/interop/package.json, packages/ipns/package.json, packages/json/package.json, packages/mfs/package.json, packages/strings/package.json, packages/unixfs/package.json, packages/utils/package.json
To enable tree shaking, add this to all modules.
=> fix: add sideEffects: false to package.json

CHANGELOG.md
updating links in root CHANGELOG.md
=> docs: update root CHANGELOG package links

packages/utils/package.json, packages/utils/src/utils/networked-storage.ts
Wraps blockstore to prevent writing identity blocks
=> fix: wrap blockstore in identity blockstore

packages/utils/src/utils/networked-storage.ts
=> fix: add missing log prefix colon for helia:session-storage

benchmarks/add-dir/package.json, benchmarks/gc/package.json, benchmarks/transfer/package.json, benchmarks/transports/package.json, benchmarks/transports/src/runner/helia/recipient.ts, benchmarks/transports/src/tests.ts
The bugs stopping WebRTC and WebTransport from being testable in browsers have been fixed and shipped so they can be added to the suite.
=> chore: update benchmarks

packages/helia/src/utils/bootstrappers.ts
Adds the new bootstrapper to the default list
=> fix: add va1 bootstrapper

FUNDING.json
IP Shipyard is applying for Optimism's retroactive public funding round for developer tooling. This PR adds a json file to associate Helia with IP Shipyard's application
=> chore: Update FUNDING.json for Optimism RPF

packages/utils/src/abstract-session.ts
=> fix: reject session block promise on abort

packages/routers/src/http-gateway-routing.ts
The fleek deployment is no longer active
=> chore: update gateway checker url

packages/unixfs/README.md, packages/unixfs/package.json, packages/unixfs/src/index.ts
docs(@helia/unixfs): example - add browser file/dir
Adds an example using [@cypsela/browser-source](https://github.com/cypsela/browser-source) to add [FileSystemEntry](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemEntry) and [FileSystemHandle](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemHandle) to @helia/unixfs
I haven't tested this fully. Thinking about making a live example.
=> docs(@helia/unixfs): example - add browser file/dir

packages/ipns/package.json, packages/ipns/src/index.ts, packages/ipns/src/ipns.ts, packages/ipns/src/utils.ts, packages/ipns/test/publish.spec.ts, packages/ipns/test/resolve.spec.ts
Also publish recursive records with PeerId and libp2p-key values
Fixes #801
=> feat: resolve IPNS records with PeerId and CID keys
